#
# SPDX-FileCopyrightText: 2026 Aayush Gupta <https://aayush.io>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# This file describes the licensing and copyright situation for files that
# cannot be annotated directly, for example because of being simply
# uncommentable. Unless this is the case, a file should be annotated directly.
#
# This follows the REUSE specification: https://reuse.software/spec-3.3/#reusetoml

version = 1

[[annotations]]
SPDX-FileCopyrightText = "2026 Aayush Gupta <https://aayush.io>"
SPDX-License-Identifier = "GPL-3.0-or-later"
path = [
  ".gitignore",
  "README.md"
]
precedence = "aggregate"
